# Site settings
title: Bohan Zhou's Personal Webpage
email: "Matthew.D.Parno@dartmouth.edu"
author: "Matthew Parno"
url: "https://math.dartmouth.edu"
baseurl: "/~bzhou"         #Change this to the local folder that stores the assets.
markdown: kramdown

exclude: ['./README.md']

# Build settings
sass:
  sass_dir: assets/css
  style: compressed

plugins:
  - jekyll-relative-links
